### ISSUE TITLE
Retiring this module (open for take-over)

### ISSUE THREAD

**Issue by jovandeginste** [jovandeginste/hiera-router#3]
If anyone really sees a need to keep the hiera-router alive, feel free to fork and/or take ownership! (Or I can keep merging PR's)

**Comment by shaman007** [comment]
Hi!

We are going to use this module in our company and I actually wanted to make some minor trivial changes.

**Comment by jovandeginste** [comment]
Would you want to take it over, or just submit the PR's?

**Comment by shaman007** [comment]
I'll take it if you're OK. PR's I make wouldn't be interested to anyone but we want to use this gem in prod.
